### ISSUE TITLE
Add active session styles

### ISSUE THREAD

**Issue by vdclouis** [sindresorhus/hyper-snazzy#15]
using the `.term_active` class in version 1 you can style the active session.
see [this](https://github.com/matheuss/hyper-simple-highlight-active-session) example

**Comment by sindresorhus** [comment]
Any suggestions on what to do with it?

**Comment by vdclouis** [comment]
maybe just an opacity change like in the example?

```css
.term_fit:not(.term_term) {
    opacity: 0.6;
}
.term_fit.term_active {
    opacity: 1;
    transition: opacity 0.12s ease-in-out;
    will-change: opacity;
}
```
